version: '3'

services:
  
  nginx:
    image: localhost/nginx
    ports:
      - 8080:8081
      - 8443:8443
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot
    networks:
      - internal
      - default

  varnish:
    image: localhost/varnish
    networks:
      - internal

  ipfs:
    image: localhost/ipfs
    expose:
      - '8080'
    ports:
      - 4001:4001
      - 5001:5001
    networks:
      - internal

volumes:
  letsencrypt:
  cerbot:

networks:
  internal:
