# This is a basic workflow to help you get started with Actions

name: terraform

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: fetch-terraform
        run: |
          wget https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip
      - name: check-hash
        run: |
          diff <(sha256sum terraform_0.15.3_linux_amd64.zip) <(echo "5ce5834fde3368ad7bdaac847f973e66e61acae469ee86b88da4c6d9f933d4  terraform_0.15.3_linux_amd64.zip")
      - name: unzip
        run: |
          unzip terraform_0.15.3_linux_amd64.zip
      - name: tf-plan
        run: |
          ./terraform plan
