name: terraform

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch-terraform-binary
        run: |
          wget https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip
      - name: check-hash
        run: |
          diff <(sha256sum terraform_0.15.3_linux_amd64.zip) <(echo "5ce5834fd74e3368ad7bdaac847f973e66e61acae469ee86b88da4c6d9f933d4  terraform_0.15.3_linux_amd64.zip")
      - name: unzip
        run: |
          unzip terraform_0.15.3_linux_amd64.zip
      - name: terraform-init
        run: |
          cd gcp
          ../terraform init
      - name: terraform-configure
        run: |
          SVCACCT=$HOME/svcacct.json
          CONFIG=$PWD/gcp/terraform.tfvars
          echo "$TERRAFORM_SVCACCT_BASE64" | base64 -d >$SVCACCT
          echo "$TERRAFORM_CONFIG_BASE64"  | base64 -d >$CONFIG
          sed -i -e "s/TERRAFORM_SVCACCT/$(echo $SVCACCT | sed -e 's/\//\\\//g')/"
      - name: terraform-plan
        run: |
          cd gcp
          ../terraform apply
